name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    strategy:
          matrix:
            run-config:
              - { scheme: GitIt, destination: 'platform=iOS Simulator,OS=15.0,name=iPhone 12' }
              
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Prepare iOS 14.5 simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_13.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.5.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 12" "com.apple.CoreSimulator.SimRuntime.iOS-14-5"
          xcrun simctl list devices 14.5
      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p
      - name: Show Build Settings
        run: xcodebuild -workspace ./GitIt.xcodeproj/project.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings
      - name: Show Build SDK
        run: xcodebuild -workspace ./GitIt.xcodeproj/project.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showsdks
      - name: Show Available Destinations
        run: xcodebuild -workspace ./GitIt.xcodeproj/project.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations   
      - name: build and test
        run: xcodebuild clean -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
        
